const TURN_PHASES = {
    DEPLOYMENT: 0,
    ATTACK: 1,
    MOVEMENT: 2
};

const GAME_PHASES = {
    PLAYER_SETUP: 0,
    GAME: 1
};

const CONSTANTS = {
    MIN_NUMBER_OF_PLAYERS: 2,
    MAX_NUMBER_OF_PLAYERS: 6,
    MIN_REINFORCEMENTS: 3
};

const MAIN_MUSIC = './audio/bgmusic.mp3';

const MUSIC_VOLUME_DURING_TUTORIAL = 0.1;

const MUSIC_VOLUME_WHEN_VOICE_IS_SPEAKING = 0.3;

const MAX_CARDS_ON_HAND = 5;

export {TURN_PHASES, GAME_PHASES, CONSTANTS, MAIN_MUSIC, MUSIC_VOLUME_WHEN_VOICE_IS_SPEAKING, MAX_CARDS_ON_HAND, MUSIC_VOLUME_DURING_TUTORIAL};
