const CARD_TYPE = {
    TROOP: 0,
    HORSE: 1,
    CANNON: 2,
    JOKER: 3
};

const CARD_COMBINATIONS = {
    THREE_TROOPS: 0,
    THREE_HORSES: 1,
    THREE_CANNONS: 2,
    ONE_OF_EACH: 3
};

export {CARD_TYPE, CARD_COMBINATIONS};
