const MESSAGE_TYPES = {
	CHECKING_FOR_UPDATES: 'CHECKING_FOR_UPDATES',
	NEW_UPDATE_AVAILABLE: 'NEW_UPDATE_AVAILABLE',
	NO_NEW_UPDATE_AVAILABLE: 'NO_NEW_UPDATE_AVAILABLE',
	UPDATE_DOWNLOADING: 'UPDATE_DOWNLOADING',
	UPDATE_DOWNLOADED: 'UPDATE_DOWNLOADED'
};

const ERROR_TYPES = {
	CONNECTION_TIMED_OUT: 'CONNECTION_TIMED_OUT',
	UNKNOWN: 'UNKNOWN',
	NO_RELEASES_COULD_BE_FETCHED: 'NO_RELEASES_COULD_BE_FETCHED'
};

module.exports = { MESSAGE_TYPES, ERROR_TYPES };